FROM openjdk:17-oracle

ARG JAR_FILE=build/libs/*.dadok.jar

ENV SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE} \
FRONT_DOMAIN: ${FRONT_DOMAIN} \
DATASOURCE_URL: ${DATASOURCE_URL} \
DATASOURCE_USERNAME: ${DATASOURCE_USERNAME} \
DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD} \
DRIVER_CLASS_NAME: ${DRIVER_CLASS_NAME} \
HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO} \
HIBERNATE_DIALECT: ${HIBERNATE_DIALECT} \
HIBERNATE_FORMAT_SQL: ${HIBERNATE_FORMAT_SQL} \
HIBERNATE_SHOW_SQL: ${HIBERNATE_SHOW_SQL} \
HIBERNATE_DEFAULT_BATCH_FETCH_SIZE: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE} \
ENABLE_JPA_OPEN_IN_VIEW: ${ENABLE_JPA_OPEN_IN_VIEW} \
DATABASE_NAME: ${DATABASE_NAME} \
ENABLE_P6SPY: ${ENABLE_P6SPY} \
JWT_SECRET_KEY: ${JWT_SECRET_KEY} \
KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID} \
KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET} \
KAKAO_REDIRECT_PATH: ${KAKAO_REDIRECT_PATH} \
NAVER_CLIENT_ID: ${NAVER_CLIENT_ID} \
NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET} \
NAVER_REDIRECT_PATH: ${NAVER_REDIRECT_PATH} \
ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS} \
REFRESH_TOKEN_EXPIRE_SECONDS: ${REFRESH_TOKEN_EXPIRE_SECONDS} \
SERVER_HOST: ${SERVER_HOST} \
KAKAO_SCHEME: ${KAKAO_SCHEME} \
KAKAO_BOOK_BASE_URI: ${KAKAO_BOOK_BASE_URI} \
SLACK_OAUTH_TOKEN: ${SLACK_OAUTH_TOKEN} \
SLACK_ERROR_CHANNEL_ID: ${SLACK_ERROR_CHANNEL_ID} \
REDIS_HOST: ${REDIS_HOST} \
REDIS_PORT: ${REDIS_PORT} \
REDIS_PASSWORD: ${REDIS_PASSWORD} \
TZ=Asia/Seoul

COPY build/libs/*.dadok.jar app.jar

ENTRYPOINT ["java", \
"-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", \
"-jar", "/app.jar"]