INSERT INTO jobs(id, job_group, job_name, sort_order, created_at, modified_at)
VALUES (1, 'DEVELOPMENT', 'DATA_ENGINEER', 1, now(), null),
       (2, 'DEVELOPMENT', 'JAVA_DEVELOPER', 2, now(), null),
       (3, 'DEVELOPMENT', 'DOTNET_DEVELOPER', 3, now(), null),
       (4, 'DEVELOPMENT', 'SYSTEM_NETWORK_ADMINISTRATOR', 4, now(), null),
       (5, 'DEVELOPMENT', 'BACKEND_DEVELOPER', 5, now(), null),
       (6, 'DEVELOPMENT', 'FRONTEND_DEVELOPER', 6, now(), null),
       (7, 'DEVELOPMENT', 'SECURITY_ENGINEER', 7, now(), null),
       (8, 'DEVELOPMENT', 'HARDWARE_ENGINEER', 8, now(), null),
       (9, 'DEVELOPMENT', 'DEVOPS', 9, now(), null),
       (10, 'DEVELOPMENT', 'QA_TEST_ENGINEER', 10, now(), null),
       (11, 'DEVELOPMENT', 'ANDROID_DEVELOPER', 11, now(), null),
       (12, 'DEVELOPMENT', 'IOS_DEVELOPER', 12, now(), null),
       (13, 'DEVELOPMENT', 'CIO', 13, now(), null),
       (14, 'DEVELOPMENT', 'CTO', 14, now(), null),
       (15, 'DEVELOPMENT', 'SERVER_DEVELOPER', 15, now(), null),
       (16, 'DEVELOPMENT', 'WEB_DEVELOPER', 16, now(), null),
       (17, 'DEVELOPMENT', 'PRODUCT_MANAGER', 17, now(), null),
       (18, 'DEVELOPMENT', 'DEVELOPMENT_MANAGER', 18, now(), null),
       (19, 'DEVELOPMENT', 'PHP_DEVELOPER', 19, now(), null),
       (20, 'DEVELOPMENT', 'RUBY_ON_RAILS_DEVELOPER', 20, now(), null),
       (21, 'DEVELOPMENT', 'NODEJS_DEVELOPER', 21, now(), null),
       (22, 'DEVELOPMENT', 'MEDIA_ENGINEER', 22, now(), null),
       (23, 'DEVELOPMENT', 'GRAPHICS_ENGINEER', 23, now(), null),
       (24, 'DEVELOPMENT', 'PYTHON_DEVELOPER', 24, now(), null),
       (25, 'DEVELOPMENT', 'C_CPP_DEVELOPER', 25, now(), null),
       (26, 'DEVELOPMENT', 'WEB_PUBLISHER', 26, now(), null),
       (27, 'DEVELOPMENT', 'BI_ENGINEER', 27, now(), null),
       (28, 'DEVELOPMENT', 'DATA_SCIENTIST', 28, now(), null),
       (29, 'DEVELOPMENT', 'BIGDATA_ENGINEER', 29, now(), null),
       (30, 'DEVELOPMENT', 'TECHNICAL_SUPPORT', 30, now(), null),
       (31, 'DEVELOPMENT', 'BLOCKCHAIN_ENGINEER', 31, now(), null),
       (32, 'DEVELOPMENT', 'MACHINE_LEARNING_ENGINEER', 32, now(), null),
       (33, 'DEVELOPMENT', 'SOFTWARE_ENGINEER', 33, now(), null),
       (34, 'DEVELOPMENT', 'CROSS_PLATFORM_APP_DEVELOPER', 34, now(), null),
       (35, 'DEVELOPMENT', 'VR_ENGINEER', 35, now(), null),
       (36, 'DEVELOPMENT', 'ERP_EXPERT', 36, now(), null),
       (37, 'DEVELOPMENT', 'ETC', 37, now(), null),
       (38, 'MANAGEMENT_BUSINESS', 'SECRETARY', 1, now(), null),
       (39, 'MANAGEMENT_BUSINESS', 'OPERATION_MANAGER', 2, now(), null),
       (40, 'MANAGEMENT_BUSINESS', 'OFFICE_MANAGER', 3, now(), null),
       (41, 'MANAGEMENT_BUSINESS', 'PM_PO', 4, now(), null),
       (42, 'MANAGEMENT_BUSINESS', 'BUSINESS_PLANNER', 5, now(), null),
       (43, 'MANAGEMENT_BUSINESS', 'SERVICE_PLANNER', 6, now(), null),
       (44, 'MANAGEMENT_BUSINESS', 'CONSULTANT', 7, now(), null),
       (45, 'MANAGEMENT_BUSINESS', 'CEO', 8, now(), null),
       (46, 'MANAGEMENT_BUSINESS', 'CFO', 9, now(), null),
       (47, 'MANAGEMENT_BUSINESS', 'COO', 10, now(), null),
       (48, 'MANAGEMENT_BUSINESS', 'CSO', 11, now(), null),
       (49, 'MANAGEMENT_BUSINESS', 'ACCOUNTANT', 12, now(), null),
       (50, 'MANAGEMENT_BUSINESS', 'OVERSEAS_BUSINESS_PLANNER', 13, now(), null),
       (51, 'MANAGEMENT_BUSINESS', 'EXHIBITION_PLANNER', 14, now(), null),
       (52, 'MANAGEMENT_BUSINESS', 'SEMINAR_FORUM_PLANNER', 15, now(), null),
       (53, 'MANAGEMENT_BUSINESS', 'PERFORMANCE_PLANNER', 16, now(), null),
       (54, 'MANAGEMENT_BUSINESS', 'AGILE_COACH', 17, now(), null),
       (55, 'MANAGEMENT_BUSINESS', 'ADMINISTRATIVE_ASSISTANT', 18, now(), null),
       (56, 'MANAGEMENT_BUSINESS', 'PRODUCT_PLANNER_BM', 19, now(), null),
       (57, 'MANAGEMENT_BUSINESS', 'ISMS', 20, now(), null),
       (58, 'MANAGEMENT_BUSINESS', 'ETC', 21, now(), null),
       (59, 'MARKETING_ADVERTISEMENT', 'BRAND_MARKETER', 1, now(), null),
       (60, 'MARKETING_ADVERTISEMENT', 'COPYWRITER', 2, now(), null),
       (61, 'MARKETING_ADVERTISEMENT', 'MARKETER', 3, now(), null),
       (62, 'MARKETING_ADVERTISEMENT', 'PR_EXPERT', 4, now(), null),
       (63, 'MARKETING_ADVERTISEMENT', 'MARKETING_PLANNER', 5, now(), null),
       (64, 'MARKETING_ADVERTISEMENT', 'SOCIAL_MEDIA_MARKETER', 6, now(), null),
       (65, 'MARKETING_ADVERTISEMENT', 'ADVERTISING_PLANNER_AE', 7, now(), null),
       (66, 'MARKETING_ADVERTISEMENT', 'CMO', 8, now(), null),
       (67, 'MARKETING_ADVERTISEMENT', 'CBO', 9, now(), null),
       (68, 'MARKETING_ADVERTISEMENT', 'GLOBAL_MARKETING', 10, now(), null),
       (69, 'MARKETING_ADVERTISEMENT', 'ETC', 11, now(), null),
       (70, 'SALES', 'SALES', 1, now(), null),
       (71, 'SALES', 'KEY_ACCOUNT_MANAGER', 2, now(), null),
       (72, 'SALES', 'SALES_ENGINEER', 3, now(), null),
       (73, 'SALES', 'SALES_MANAGER', 4, now(), null),
       (74, 'SALES', 'SOLUTION_CONSULTANT', 5, now(), null),
       (75, 'SALES', 'CUSTOMER_SUCCESS_MANAGER', 6, now(), null),
       (76, 'SALES', 'ETC', 7, now(), null),
       (77, 'CUSTOMER_SERVICE_RETAIL', 'CS_ADVISOR', 1, now(), null),
       (78, 'CUSTOMER_SERVICE_RETAIL', 'FLIGHT_ATTENDANT', 2, now(), null),
       (79, 'CUSTOMER_SERVICE_RETAIL', 'AS_TECHNICIAN', 3, now(), null),
       (80, 'CUSTOMER_SERVICE_RETAIL', 'EVENT_PLANNER', 4, now(), null),
       (81, 'CUSTOMER_SERVICE_RETAIL', 'FLORIST', 5, now(), null),
       (82, 'CUSTOMER_SERVICE_RETAIL', 'TRAVEL_AGENT', 6, now(), null),
       (83, 'CUSTOMER_SERVICE_RETAIL', 'STORE_MANAGER', 7, now(), null),
       (84, 'CUSTOMER_SERVICE_RETAIL', 'STORE_STAFF', 8, now(), null),
       (85, 'CUSTOMER_SERVICE_RETAIL', 'SKIN_CARE_SPECIALIST', 9, now(), null),
       (86, 'CUSTOMER_SERVICE_RETAIL', 'HAIR_DESIGNER', 10, now(), null),
       (87, 'CUSTOMER_SERVICE_RETAIL', 'VISUAL_MECHANDISER', 11, now(), null),
       (88, 'CUSTOMER_SERVICE_RETAIL', 'MD', 12, now(), null),
       (89, 'CUSTOMER_SERVICE_RETAIL', 'INBOUND_TELEMARKETER', 13, now(), null),
       (90, 'CUSTOMER_SERVICE_RETAIL', 'CRM_EXPERT', 14, now(), null),
       (91, 'CUSTOMER_SERVICE_RETAIL', 'OUTBOUND_TELEMARKETER', 15, now(), null),
       (92, 'CUSTOMER_SERVICE_RETAIL', 'CS_MANAGER', 16, now(), null),
       (93, 'CUSTOMER_SERVICE_RETAIL', 'HEALTHCARE_MANAGER', 17, now(), null),
       (94, 'CUSTOMER_SERVICE_RETAIL', 'BEAUTICIAN', 18, now(), null),
       (95, 'CUSTOMER_SERVICE_RETAIL', 'PET_BEAUTICIAN', 19, now(), null),
       (96, 'CUSTOMER_SERVICE_RETAIL', 'RECEPTIONIST', 20, now(), null),
       (97, 'CUSTOMER_SERVICE_RETAIL', 'ETC', 21, now(), null),
       (98, 'MEDIA', 'VIDEO_EDITOR', 1, now(), null),
       (99, 'MEDIA', 'WRITER', 2, now(), null),
       (100, 'MEDIA', 'EDITOR', 3, now(), null),
       (101, 'MEDIA', 'JOURNALIST', 4, now(), null),
       (102, 'MEDIA', 'PD', 5, now(), null),
       (103, 'MEDIA', 'REPORTER', 6, now(), null),
       (104, 'MEDIA', 'PHOTOGRAPHER', 7, now(), null),
       (105, 'MEDIA', 'TRANSLATOR_INTERPRETER', 8, now(), null),
       (106, 'MEDIA', 'PUBLISHING_PLANNER', 9, now(), null),
       (107, 'MEDIA', 'AUDIO_ENGINEER', 10, now(), null),
       (108, 'MEDIA', 'CURATOR', 11, now(), null),
       (109, 'MEDIA', 'CONTENT_CREATOR', 12, now(), null),
       (110, 'MEDIA', 'ENTERTAINMENT', 13, now(), null),
       (111, 'MEDIA', 'ETC', 14, now(), null),
       (112, 'GAME', 'UNITY_DEVELOPER', 1, now(), null),
       (113, 'GAME', 'GAME_GRAPHIC_DESIGNER', 2, now(), null),
       (114, 'GAME', 'GAME_ARTIST', 3, now(), null),
       (115, 'GAME', 'GAME_PLANNER', 4, now(), null),
       (116, 'GAME', 'UNREAL_DEVELOPER', 5, now(), null),
       (117, 'GAME', 'GAME_OPERATOR_GM', 6, now(), null),
       (118, 'GAME', 'GAME_SERVER_DEVELOPER', 7, now(), null),
       (119, 'GAME', 'GAME_CLIENT_DEVELOPER', 8, now(), null),
       (120, 'GAME', 'MOBILE_GAME_DEVELOPER', 9, now(), null),
       (121, 'GAME', 'ETC', 10, now(), null),
       (122, 'HR', 'TEACHER', 1, now(), null),
       (123, 'HR', 'TECHNICAL_EDUCATION', 2, now(), null),
       (124, 'HR', 'HR_CONSULTANT', 3, now(), null),
       (125, 'HR', 'PERSONNEL_MANAGER', 4, now(), null),
       (126, 'HR', 'RECRUITER', 5, now(), null),
       (127, 'HR', 'HRD', 6, now(), null),
       (128, 'HR', 'ORGANIZATIONAL_CULTURE', 7, now(), null),
       (129, 'HR', 'SALARY_ADMINISTRATOR', 8, now(), null),
       (130, 'HR', 'E_LEARNING', 9, now(), null),
       (131, 'HR', 'HEADHUNTER', 10, now(), null),
       (132, 'HR', 'PROFESSOR', 11, now(), null),
       (133, 'HR', 'HRBP', 12, now(), null),
       (134, 'HR', 'ETC', 13, now(), null),
       (135, 'ENGINEERING_DESIGN', 'AEROSPACE_ENGINEER', 1, now(), null),
       (136, 'ENGINEERING_DESIGN', 'AGRICULTURAL_ENGINEER', 2, now(), null),
       (137, 'ENGINEERING_DESIGN', 'AUTOMOTIVE_ENGINEER', 3, now(), null),
       (138, 'ENGINEERING_DESIGN', 'GENETIC_ENGINEER', 4, now(), null),
       (139, 'ENGINEERING_DESIGN', 'BIOMEDICAL_ENGINEER', 5, now(), null),
       (140, 'ENGINEERING_DESIGN', 'CERAMIC_ENGINEER', 6, now(), null),
       (141, 'ENGINEERING_DESIGN', 'CHEMICAL_ENGINEER', 7, now(), null),
       (142, 'ENGINEERING_DESIGN', 'CIVIL_ENGINEERING_TECHNICIAN', 8, now(), null),
       (143, 'ENGINEERING_DESIGN', 'COMMISSIONING_ENGINEER', 9, now(), null),
       (144, 'ENGINEERING_DESIGN', 'CONSTRUCTION_ENGINEER', 10, now(), null),
       (145, 'ENGINEERING_DESIGN', 'CONTROL_ENGINEER', 11, now(), null),
       (146, 'ENGINEERING_DESIGN', 'DRAFTING_TECHNICIAN', 12, now(), null),
       (147, 'ENGINEERING_DESIGN', 'DRILLING_ENGINEER', 13, now(), null),
       (148, 'ENGINEERING_DESIGN', 'ELECTRICAL_ENGINEER', 14, now(), null),
       (149, 'ENGINEERING_DESIGN', 'ELECTROMECHANICAL_ENGINEER', 15, now(), null),
       (150, 'ENGINEERING_DESIGN', 'ELECTRONICS_ENGINEER', 16, now(), null),
       (151, 'ENGINEERING_DESIGN', 'ENVIRONMENTAL_ENGINEER', 17, now(), null),
       (152, 'ENGINEERING_DESIGN', 'EQUIPMENT_ENGINEER', 18, now(), null),
       (153, 'ENGINEERING_DESIGN', 'FACILITY_ENGINEER', 19, now(), null),
       (154, 'ENGINEERING_DESIGN', 'FIRE_SAFETY_TECHNICIAN', 20, now(), null),
       (155, 'ENGINEERING_DESIGN', 'GEOGRAPHER', 21, now(), null),
       (156, 'ENGINEERING_DESIGN', 'GEOLOGICAL_ENGINEER', 22, now(), null),
       (157, 'ENGINEERING_DESIGN', 'INDUSTRIAL_ENGINEER', 23, now(), null),
       (158, 'ENGINEERING_DESIGN', 'INSTRUMENTATION_AND_CONTROL_ENGINEER', 24, now(), null),
       (159, 'ENGINEERING_DESIGN', 'MANUFACTURING_ENGINEER', 25, now(), null),
       (160, 'ENGINEERING_DESIGN', 'MARINE_ENGINEER', 26, now(), null),
       (161, 'ENGINEERING_DESIGN', 'MATERIALS_ENGINEER', 27, now(), null),
       (162, 'ENGINEERING_DESIGN', 'MECHANICAL_ENGINEER', 28, now(), null),
       (163, 'ENGINEERING_DESIGN', 'METALLURGICAL_ENGINEER', 29, now(), null),
       (164, 'ENGINEERING_DESIGN', 'MINING_TECHNICIAN', 30, now(), null),
       (165, 'ENGINEERING_DESIGN', 'NAVAL_ARCHITECT', 31, now(), null),
       (166, 'ENGINEERING_DESIGN', 'NUCLEAR_ENERGY_ENGINEER', 32, now(), null),
       (167, 'ENGINEERING_DESIGN', 'OIL_ENGINEER', 33, now(), null),
       (168, 'ENGINEERING_DESIGN', 'PIPELINE_DESIGN_ENGINEER', 34, now(), null),
       (169, 'ENGINEERING_DESIGN', 'PLANT_ENGINEER', 35, now(), null),
       (170, 'ENGINEERING_DESIGN', 'PROCESS_ENGINEER', 36, now(), null),
       (171, 'ENGINEERING_DESIGN', 'PRODUCT_ENGINEER', 37, now(), null),
       (172, 'ENGINEERING_DESIGN', 'PROJECT_ENGINEER', 38, now(), null),
       (173, 'ENGINEERING_DESIGN', 'QA_ENGINEER', 39, now(), null),
       (174, 'ENGINEERING_DESIGN', 'QC_ENGINEER', 40, now(), null),
       (175, 'ENGINEERING_DESIGN', 'ELECTRICAL_POWER_ENGINEER', 41, now(), null),
       (176, 'ENGINEERING_DESIGN', 'RESERVOIR_ENGINEER', 42, now(), null),
       (177, 'ENGINEERING_DESIGN', 'RF_ENGINEER', 43, now(), null),
       (178, 'ENGINEERING_DESIGN', 'ROTATING_EQUIPMENT_ENGINEER', 44, now(), null),
       (179, 'ENGINEERING_DESIGN', 'STRUCTURAL_ENGINEER', 45, now(), null),
       (180, 'ENGINEERING_DESIGN', 'TURBINE_ENGINEER', 46, now(), null),
       (181, 'ENGINEERING_DESIGN', 'CAD_3D_DESIGNER', 47, now(), null),
       (182, 'ENGINEERING_DESIGN', 'ROBOT_AUTOMATION', 48, now(), null),
       (183, 'ENGINEERING_DESIGN', 'ETC', 49, now(), null),
       (184, 'FINANCE', 'ACCOUNTANT', 1, now(), null),
       (185, 'FINANCE', 'FINANCIAL_ANALYST', 2, now(), null),
       (186, 'FINANCE', 'CERTIFIED_PUBLIC_ACCOUNTANT', 3, now(), null),
       (187, 'FINANCE', 'INTERNAL_CONTROL_SPECIALIST', 4, now(), null),
       (188, 'FINANCE', 'INSURANCE_AGENT', 5, now(), null),
       (189, 'FINANCE', 'ADJUSTER', 6, now(), null),
       (190, 'FINANCE', 'CLAIMS_ADJUSTER', 7, now(), null),
       (191, 'FINANCE', 'UNDERWRITER', 8, now(), null),
       (192, 'FINANCE', 'REAL_ESTATE_ASSET_MANAGER', 9, now(), null),
       (193, 'FINANCE', 'REAL_ESTATE_AGENT', 10, now(), null),
       (194, 'FINANCE', 'APPRAISER', 11, now(), null),
       (195, 'FINANCE', 'ANALYST', 12, now(), null),
       (196, 'FINANCE', 'INVESTOR_RELATIONS', 13, now(), null),
       (197, 'FINANCE', 'TRADER', 14, now(), null),
       (198, 'FINANCE', 'FINANCIAL_ENGINEER', 15, now(), null),
       (199, 'FINANCE', 'ASSET_MANAGER', 16, now(), null),
       (200, 'FINANCE', 'ASSET_MANAGER', 17, now(), null),
       (201, 'FINANCE', 'INVESTMENT_BANKER', 18, now(), null),
       (202, 'FINANCE', 'COMPLIANCE_OFFICER', 19, now(), null),
       (203, 'FINANCE', 'TAX_ACCOUNTANT', 20, now(), null),
       (204, 'FINANCE', 'FINANCIAL_MANAGER', 21, now(), null),
       (205, 'FINANCE', 'INVESTMENT_SECURITIES', 22, now(), null),
       (206, 'FINANCE', 'ETC', 23, now(), null),
       (207, 'MANUFACTURING', 'ASSEMBLY_TECHNICIAN', 1, now(), null),
       (208, 'MANUFACTURING', 'CHEMIST', 2, now(), null),
       (209, 'MANUFACTURING', 'MECHANICAL_TECHNICIAN', 3, now(), null),
       (210, 'MANUFACTURING', 'MANUFACTURING_ENGINEER', 4, now(), null),
       (211, 'MANUFACTURING', 'MECHANICAL_FACILITY_DESIGN', 5, now(), null),
       (212, 'MANUFACTURING', 'PRODUCTION_MANAGER', 6, now(), null),
       (213, 'MANUFACTURING', 'PRODUCTION_WORKER', 7, now(), null),
       (214, 'MANUFACTURING', 'PROCESS_MANAGER', 8, now(), null),
       (215, 'MANUFACTURING', 'QUALITY_MANAGER', 9, now(), null),
       (216, 'MANUFACTURING', 'SAFETY_MANAGER', 10, now(), null),
       (217, 'MANUFACTURING', 'TEST_ENGINEER', 11, now(), null),
       (218, 'MANUFACTURING', 'TEXTILES_APPAREL_FASHION', 12, now(), null),
       (219, 'MANUFACTURING', 'SEMICONDUCTOR_DISPLAY', 13, now(), null),
       (220, 'MANUFACTURING', 'ETC', 14, now(), null),
       (221, 'MEDICAL', 'DENTAL_HYGIENIST', 1, now(), null),
       (222, 'MEDICAL', 'PARALEGAL', 2, now(), null),
       (223, 'MEDICAL', 'CLINICAL_LABORATORY_TECHNOLOGIST', 3, now(), null),
       (224, 'MEDICAL', 'NURSE', 4, now(), null),
       (225, 'MEDICAL', 'PHYSICAL_THERAPIST', 5, now(), null),
       (226, 'MEDICAL', 'PHYSICIAN', 6, now(), null),
       (227, 'MEDICAL', 'VETERINARIAN', 7, now(), null),
       (228, 'MEDICAL', 'NURSE_PARALEGAL', 8, now(), null),
       (229, 'MEDICAL', 'DENTIST', 9, now(), null),
       (230, 'MEDICAL', 'EXAMINER', 10, now(), null),
       (231, 'MEDICAL', 'PHARMACIST', 11, now(), null),
       (232, 'MEDICAL', 'CLINICAL_TRIAL_RESEARCHER', 12, now(), null),
       (233, 'MEDICAL', 'CLINICAL_TRIAL_NURSE', 13, now(), null),
       (234, 'MEDICAL', 'MICROBIOLOGIST', 14, now(), null),
       (235, 'MEDICAL', 'GENETICIST', 15, now(), null),
       (236, 'MEDICAL', 'RESEARCHER', 16, now(), null),
       (237, 'MEDICAL', 'ORIENTAL_MEDICINE_PHYSICIAN', 17, now(), null),
       (238, 'MEDICAL', 'RADIOLOGIST', 18, now(), null),
       (239, 'MEDICAL', 'HOSPITAL_COORDINATOR', 19, now(), null),
       (240, 'MEDICAL', 'CLINICAL_PSYCHOLOGIST', 20, now(), null),
       (241, 'MEDICAL', 'ETC', 21, now(), null),
       (242, 'LOGISTICS', 'SHIPPING_HANDLER', 1, now(), null),
       (243, 'LOGISTICS', 'DIESEL_MECHANIC', 2, now(), null),
       (244, 'LOGISTICS', 'OPERATIONS_MANAGER', 3, now(), null),
       (245, 'LOGISTICS', 'FORKLIFT_DRIVER', 4, now(), null),
       (246, 'LOGISTICS', 'DRIVER', 5, now(), null),
       (247, 'LOGISTICS', 'LOGISTICS_ANALYST', 6, now(), null),
       (248, 'LOGISTICS', 'FREIGHT_TRUCK_DRIVER', 7, now(), null),
       (249, 'LOGISTICS', 'SHIPPING_CLERK', 8, now(), null),
       (250, 'LOGISTICS', 'TRANSPORTATION_MANAGER', 9, now(), null),
       (251, 'LOGISTICS', 'WAREHOUSE_WORKER', 10, now(), null),
       (252, 'LOGISTICS', 'AIR_TRANSPORTATION', 11, now(), null),
       (253, 'LOGISTICS', 'MARINE_TRANSPORTATION', 12, now(), null),
       (254, 'LOGISTICS', 'TRADE_OFFICE', 13, now(), null),
       (255, 'LOGISTICS', 'CUSTOMS_BROKER', 14, now(), null),
       (256, 'LOGISTICS', 'ORIGIN_MANAGEMENT_SPECIALIST', 15, now(), null),
       (257, 'LOGISTICS', 'INBOUND_OUTBOUND_MANAGER', 16, now(), null),
       (258, 'LOGISTICS', 'DISTRIBUTION_MANAGER', 17, now(), null),
       (259, 'LOGISTICS', 'MARINE_NAVIGATION_OFFICER', 18, now(), null),
       (260, 'LOGISTICS', 'MECHANICAL_OFFICER', 19, now(), null),
       (261, 'LOGISTICS', 'ETC', 20, now(), null),
       (262, 'EDUCATION', 'CURRICULUM_PLANNER', 1, now(), null),
       (263, 'EDUCATION', 'PRIVATE_TUTOR', 2, now(), null),
       (264, 'EDUCATION', 'SCHOOL_STAFF', 3, now(), null),
       (265, 'EDUCATION', 'KINDERGARTEN_TEACHER', 4, now(), null),
       (266, 'EDUCATION', 'TEACHER', 5, now(), null),
       (267, 'EDUCATION', 'QUALIFICATION_TECHNICAL_INSTRUCTOR', 6, now(), null),
       (268, 'EDUCATION', 'ETC', 7, now(), null),
       (269, 'FOOD_BEVERAGE', 'NUTRITIONIST', 1, now(), null),
       (270, 'FOOD_BEVERAGE', 'CHEF_BAKER', 2, now(), null),
       (271, 'FOOD_BEVERAGE', 'BARTENDER', 3, now(), null),
       (272, 'FOOD_BEVERAGE', 'COOK', 4, now(), null),
       (273, 'FOOD_BEVERAGE', 'FOOD_SERVICE_WORKER', 5, now(), null),
       (274, 'FOOD_BEVERAGE', 'RESTAURANT_MANAGER', 6, now(), null),
       (275, 'FOOD_BEVERAGE', 'FOOD_MD', 7, now(), null),
       (276, 'FOOD_BEVERAGE', 'FOOD_STYLIST', 8, now(), null),
       (277, 'FOOD_BEVERAGE', 'SOMMELIER', 9, now(), null),
       (278, 'FOOD_BEVERAGE', 'FOOD_PROCESSING_DEVELOPMENT', 10, now(), null),
       (279, 'FOOD_BEVERAGE', 'BARISTA', 11, now(), null),
       (280, 'FOOD_BEVERAGE', 'ETC', 12, now(), null),
       (281, 'CONSTRUCTION_FACILITY', 'CARPENTER', 1, now(), null),
       (282, 'CONSTRUCTION_FACILITY', 'HEAVY_EQUIPMENT_TECHNICIAN', 2, now(), null),
       (283, 'CONSTRUCTION_FACILITY', 'MAINTENANCE_WORKER', 3, now(), null),
       (284, 'CONSTRUCTION_FACILITY', 'MAINTENANCE_MANAGER', 4, now(), null),
       (285, 'CONSTRUCTION_FACILITY', 'FACILITY_MANAGER', 5, now(), null),
       (286, 'CONSTRUCTION_FACILITY', 'ELECTRICIAN', 6, now(), null),
       (287, 'CONSTRUCTION_FACILITY', 'PLANT_MANAGER', 7, now(), null),
       (288, 'CONSTRUCTION_FACILITY', 'WELDER', 8, now(), null),
       (289, 'CONSTRUCTION_FACILITY', 'PLUMBER', 9, now(), null),
       (290, 'CONSTRUCTION_FACILITY', 'ESTIMATOR', 10, now(), null),
       (291, 'CONSTRUCTION_FACILITY', 'ARCHITECT', 11, now(), null),
       (292, 'CONSTRUCTION_FACILITY', 'INTERIOR_ARCHITECT', 12, now(), null),
       (293, 'CONSTRUCTION_FACILITY', 'CONSTRUCTION_SUPERVISOR', 13, now(), null),
       (294, 'CONSTRUCTION_FACILITY', 'ETC', 14, now(), null),
       (295, 'PUBLIC_WELFARE', 'COUNSELOR', 1, now(), null),
       (296, 'PUBLIC_WELFARE', 'FIREFIGHTER', 2, now(), null),
       (297, 'PUBLIC_WELFARE', 'ENVIRONMENTAL_EXPERT', 3, now(), null),
       (298, 'PUBLIC_WELFARE', 'INFORMATION_ANALYST', 4, now(), null),
       (299, 'PUBLIC_WELFARE', 'LIFEGUARD', 5, now(), null),
       (300, 'PUBLIC_WELFARE', 'REGIONAL_EXPERT', 6, now(), null),
       (301, 'PUBLIC_WELFARE', 'PUBLIC_OFFICIAL', 7, now(), null),
       (302, 'PUBLIC_WELFARE', 'PROFESSIONAL_SOLDIER', 8, now(), null),
       (303, 'PUBLIC_WELFARE', 'VOLUNTEER', 9, now(), null),
       (304, 'PUBLIC_WELFARE', 'SOCIAL_WORKER', 10, now(), null),
       (305, 'PUBLIC_WELFARE', 'PARAMEDIC', 11, now(), null),
       (306, 'PUBLIC_WELFARE', 'CAREGIVER', 12, now(), null),
       (307, 'PUBLIC_WELFARE', 'ETC', 13, now(), null);


INSERT INTO users(id, created_at, modified_at, auth_id, auth_provider, birthday, email, gender, name, nickname,
                  profile_image, job_id)
VALUES (1, now(), null, 'auth_id', 'NAVER', null, 'user1@naver.com', 'MALE', 'user1', '다독이', null, 1),
       (2, now(), null, 'auth_id', 'NAVER', null, 'user2@naver.com', 'MALE', 'user2', '이다독', null, 2),
       (3, now(), null, 'auth_id', 'NAVER', null, 'user3@naver.com', 'MALE', 'user3', '한다독', null, 3),
       (4, now(), null, 'auth_id', 'NAVER', null, 'user4@naver.com', 'MALE', 'user4', '독다김', null, 4),
       (5, now(), null, 'auth_id', 'NAVER', null, 'user5@naver.com', 'MALE', 'user5', '독다독다', null, 5),
       (6, now(), null, 'auth_id', 'NAVER', null, 'user6@naver.com', 'MALE', 'user6', '독d독d', null, 6),
       (7, now(), null, 'auth_id', 'NAVER', null, 'user7@naver.com', 'MALE', 'user7', '다독2', null, 7),
       (8, now(), null, 'auth_id', 'NAVER', null, 'user8@naver.com', 'MALE', 'user8', 'da독이', null, 8),
       (9, now(), null, 'auth_id', 'NAVER', null, 'user9@naver.com', 'MALE', 'user9', '다dog이', null, 9),
       (10, now(), null, 'auth_id', 'NAVER', null, 'user10@naver.com', 'MALE', 'user10', '아령하세요', null, 10),
       (11, now(), null, 'auth_id', 'NAVER', null, 'user11@naver.com', 'MALE', 'user11', '다독이11', null, 11),
       (12, now(), null, 'auth_id', 'NAVER', null, 'user12@naver.com', 'MALE', 'user12', '다독이12', null, 12),
       (13, now(), null, 'auth_id', 'NAVER', null, 'user13@naver.com', 'MALE', 'user13', '다독이13', null, 13),
       (14, now(), null, 'auth_id', 'NAVER', null, 'user14@naver.com', 'MALE', 'user14', '다독이14', null, 14),
       (15, now(), null, 'auth_id', 'NAVER', null, 'user15@naver.com', 'MALE', 'user15', '다독이15', null, 15),
       (16, now(), null, 'auth_id', 'NAVER', null, 'user16@naver.com', 'MALE', 'user16', '다독이16', null, 16),
       (17, now(), null, 'auth_id', 'NAVER', null, 'user17@naver.com', 'MALE', 'user17', '독다독다17', null, 17),
       (18, now(), null, 'auth_id', 'NAVER', null, 'user18@naver.com', 'MALE', 'user18', '독다독다18', null, 18),
       (19, now(), null, 'auth_id', 'NAVER', null, 'user19@naver.com', 'MALE', 'user19', '독다독다19', null, 19),
       (20, now(), null, 'auth_id', 'NAVER', null, 'user20@naver.com', 'MALE', 'user20', '독다독다20', null, 20),
       (21, now(), null, 'auth_id', 'NAVER', null, 'user21@naver.com', 'MALE', 'user21', '독다독다21', null, 21),
       (22, now(), null, 'auth_id', 'NAVER', null, 'user22@naver.com', 'MALE', 'user22', '독다독다22', null, 22),
       (23, now(), null, 'auth_id', 'NAVER', null, 'user23@naver.com', 'MALE', 'user23', '독다독다23', null, 23),
       (24, now(), null, 'auth_id', 'NAVER', null, 'user24@naver.com', 'MALE', 'user24', '독다독다24', null, 24),
       (25, now(), null, 'auth_id', 'NAVER', null, 'user25@naver.com', 'MALE', 'user25', '독다독다25', null, 25),
       (26, now(), null, 'auth_id', 'NAVER', null, 'user26@naver.com', 'MALE', 'user26', '독다독다26', null, 26),
       (27, now(), null, 'auth_id', 'NAVER', null, 'user27@naver.com', 'MALE', 'user27', '다독다독운영자', null, 27),
       (28, now(), null, 'auth_id', 'NAVER', null, 'user28@naver.com', 'MALE', 'user28', '다독다독트롤', null, 28),
       (29, now(), null, 'auth_id', 'NAVER', null, 'user29@naver.com', 'MALE', 'user29', '이도닥', null, 29),
       (30, now(), null, 'auth_id', 'NAVER', null, 'user30@naver.com', 'MALE', 'user30', '안녕234', null, 30),
       (31, now(), null, 'auth_id', 'NAVER', null, 'user31@naver.com', 'MALE', 'user31', '하세요31', null, 31),
       (32, now(), null, 'auth_id', 'NAVER', null, 'user32@naver.com', 'MALE', 'user32', 'user32', null, 32),
       (33, now(), null, 'auth_id', 'NAVER', null, 'user33@naver.com', 'MALE', 'user33', 'user33', null, 33),
       (34, now(), null, 'auth_id', 'NAVER', null, 'user34@naver.com', 'MALE', 'user34', 'user34', null, 34),
       (35, now(), null, 'auth_id', 'NAVER', null, 'user35@naver.com', 'MALE', 'user35', 'user35', null, 35),
       (36, now(), null, 'auth_id', 'NAVER', null, 'user36@naver.com', 'MALE', 'user36', 'user36', null, 36),
       (37, now(), null, 'auth_id', 'NAVER', null, 'user37@naver.com', 'MALE', 'user37', 'user37', null, 37),
       (38, now(), null, 'auth_id', 'NAVER', null, 'user38@naver.com', 'MALE', 'user38', 'user38', null, 38),
       (39, now(), null, 'auth_id', 'NAVER', null, 'user39@naver.com', 'MALE', 'user39', 'user39', null, 39),
       (40, now(), null, 'auth_id', 'NAVER', null, 'user40@naver.com', 'MALE', 'user40', '김흥미40', null, 40),
       (41, now(), null, 'auth_id', 'NAVER', null, 'user41@naver.com', 'MALE', 'user41', '김흥미41', null, 41),
       (42, now(), null, 'auth_id', 'NAVER', null, 'user42@naver.com', 'MALE', 'user42', '김흥미42', null, 42),
       (43, now(), null, 'auth_id', 'NAVER', null, 'user43@naver.com', 'MALE', 'user43', '김흥미43', null, 43),
       (44, now(), null, 'auth_id', 'NAVER', null, 'user44@naver.com', 'MALE', 'user44', '김흥미44', null, 44),
       (45, now(), null, 'auth_id', 'NAVER', null, 'user45@naver.com', 'MALE', 'user45', '김흥미45', null, 45),
       (46, now(), null, 'auth_id', 'NAVER', null, 'user46@naver.com', 'MALE', 'user46', '김흥미46', null, 46),
       (47, now(), null, 'auth_id', 'NAVER', null, 'user47@naver.com', 'MALE', 'user47', '김흥미47', null, 47),
       (48, now(), null, 'auth_id', 'NAVER', null, 'user48@naver.com', 'MALE', 'user48', '김흥미48', null, 48),
       (49, now(), null, 'auth_id', 'NAVER', null, 'user49@naver.com', 'MALE', 'user49', '김흥미49', null, 49),
       (50, now(), null, 'auth_id', 'NAVER', null, 'user50@naver.com', 'MALE', 'user50', '김흥미50', null, 50),
       (51, now(), null, 'auth_id', 'NAVER', null, 'user51@naver.com', 'MALE', 'user51', '김흥미51', null, 51),
       (52, now(), null, 'auth_id', 'NAVER', null, 'user52@naver.com', 'MALE', 'user52', '독서왕52', null, 52),
       (53, now(), null, 'auth_id', 'NAVER', null, 'user53@naver.com', 'MALE', 'user53', '독서왕53', null, 53),
       (54, now(), null, 'auth_id', 'NAVER', null, 'user54@naver.com', 'MALE', 'user54', '독서왕54', null, 54),
       (55, now(), null, 'auth_id', 'NAVER', null, 'user55@naver.com', 'MALE', 'user55', '독서왕55', null, 55),
       (56, now(), null, 'auth_id', 'NAVER', null, 'user56@naver.com', 'MALE', 'user56', '독서왕56', null, 56),
       (57, now(), null, 'auth_id', 'NAVER', null, 'user57@naver.com', 'MALE', 'user57', '독서왕57', null, 57),
       (58, now(), null, 'auth_id', 'NAVER', null, 'user58@naver.com', 'MALE', 'user58', '독서왕58', null, 58),
       (59, now(), null, 'auth_id', 'NAVER', null, 'user59@naver.com', 'MALE', 'user59', '독서왕59', null, 59),
       (60, now(), null, 'auth_id', 'NAVER', null, 'user60@naver.com', 'MALE', 'user60', '독서왕60', null, 60),
       (61, now(), null, 'auth_id', 'NAVER', null, 'user61@naver.com', 'FEMALE', 'user61', 'user61', null, 1),
       (62, now(), null, 'auth_id', 'NAVER', null, 'user62@naver.com', 'FEMALE', 'user62', 'user62', null, 2),
       (63, now(), null, 'auth_id', 'NAVER', null, 'user63@naver.com', 'FEMALE', 'user63', 'user63', null, 3),
       (64, now(), null, 'auth_id', 'NAVER', null, 'user64@naver.com', 'FEMALE', 'user64', 'user64', null, 4),
       (65, now(), null, 'auth_id', 'NAVER', null, 'user65@naver.com', 'FEMALE', 'user65', 'user65', null, 5),
       (66, now(), null, 'auth_id', 'NAVER', null, 'user66@naver.com', 'FEMALE', 'user66', 'user66', null, 6),
       (67, now(), null, 'auth_id', 'NAVER', null, 'user67@naver.com', 'FEMALE', 'user67', 'user67', null, 7),
       (68, now(), null, 'auth_id', 'NAVER', null, 'user68@naver.com', 'FEMALE', 'user68', 'user68', null, 8),
       (69, now(), null, 'auth_id', 'NAVER', null, 'user69@naver.com', 'FEMALE', 'user69', 'user69', null, 9),
       (70, now(), null, 'auth_id', 'NAVER', null, 'user70@naver.com', 'FEMALE', 'user70', 'user70', null, 10),
       (71, now(), null, 'auth_id', 'NAVER', null, 'user71@naver.com', 'FEMALE', 'user71', 'user71', null, 11),
       (72, now(), null, 'auth_id', 'NAVER', null, 'user72@naver.com', 'FEMALE', 'user72', 'user72', null, 12),
       (73, now(), null, 'auth_id', 'NAVER', null, 'user73@naver.com', 'FEMALE', 'user73', 'user73', null, 13),
       (74, now(), null, 'auth_id', 'NAVER', null, 'user74@naver.com', 'FEMALE', 'user74', 'user74', null, 14),
       (75, now(), null, 'auth_id', 'NAVER', null, 'user75@naver.com', 'FEMALE', 'user75', 'user75', null, 15),
       (76, now(), null, 'auth_id', 'NAVER', null, 'user76@naver.com', 'FEMALE', 'user76', 'user76', null, 16),
       (77, now(), null, 'auth_id', 'NAVER', null, 'user77@naver.com', 'FEMALE', 'user77', 'user77', null, 17),
       (78, now(), null, 'auth_id', 'NAVER', null, 'user78@naver.com', 'FEMALE', 'user78', 'user78', null, 18),
       (79, now(), null, 'auth_id', 'NAVER', null, 'user79@naver.com', 'FEMALE', 'user79', 'user79', null, 19),
       (80, now(), null, 'auth_id', 'NAVER', null, 'user80@naver.com', 'FEMALE', 'user80', 'user80', null, 20),
       (81, now(), null, 'auth_id', 'NAVER', null, 'user81@naver.com', 'FEMALE', 'user81', 'user81', null, 21),
       (82, now(), null, 'auth_id', 'NAVER', null, 'user82@naver.com', 'FEMALE', 'user82', 'user82', null, 22),
       (83, now(), null, 'auth_id', 'NAVER', null, 'user83@naver.com', 'FEMALE', 'user83', 'user83', null, 23),
       (84, now(), null, 'auth_id', 'NAVER', null, 'user84@naver.com', 'FEMALE', 'user84', 'user84', null, 24),
       (85, now(), null, 'auth_id', 'NAVER', null, 'user85@naver.com', 'FEMALE', 'user85', 'user85', null, 25),
       (86, now(), null, 'auth_id', 'NAVER', null, 'user86@naver.com', 'FEMALE', 'user86', 'user86', null, 26),
       (87, now(), null, 'auth_id', 'NAVER', null, 'user87@naver.com', 'FEMALE', 'user87', 'user87', null, 27),
       (88, now(), null, 'auth_id', 'NAVER', null, 'user88@naver.com', 'FEMALE', 'user88', 'user88', null, 28),
       (89, now(), null, 'auth_id', 'NAVER', null, 'user89@naver.com', 'FEMALE', 'user89', 'user89', null, 29),
       (90, now(), null, 'auth_id', 'NAVER', null, 'user90@naver.com', 'FEMALE', 'user90', 'user90', null, 30),
       (91, now(), null, 'auth_id', 'NAVER', null, 'user91@naver.com', 'FEMALE', 'user91', 'user91', null, 31),
       (92, now(), null, 'auth_id', 'NAVER', null, 'user92@naver.com', 'FEMALE', 'user92', 'user92', null, 32),
       (93, now(), null, 'auth_id', 'NAVER', null, 'user93@naver.com', 'FEMALE', 'user93', 'user93', null, 33),
       (94, now(), null, 'auth_id', 'NAVER', null, 'user94@naver.com', 'FEMALE', 'user94', 'user94', null, 34),
       (95, now(), null, 'auth_id', 'NAVER', null, 'user95@naver.com', 'FEMALE', 'user95', 'user95', null, 35),
       (96, now(), null, 'auth_id', 'NAVER', null, 'user96@naver.com', 'FEMALE', 'user96', 'user96', null, 36),
       (97, now(), null, 'auth_id', 'NAVER', null, 'user97@naver.com', 'FEMALE', 'user97', 'user97', null, 37),
       (98, now(), null, 'auth_id', 'NAVER', null, 'user98@naver.com', 'FEMALE', 'user98', 'user98', null, 38),
       (99, now(), null, 'auth_id', 'NAVER', null, 'user99@naver.com', 'FEMALE', 'user99', 'user99', null, 39),
       (100, now(), null, 'auth_id', 'NAVER', null, 'user100@naver.com', 'FEMALE', 'user100', 'user100', null, 40);
